crawler:
  concurrency:
    limit: ${CRAWLER_CONCURRENCY_LIMIT:512}
  client:
    pool:
      size: ${CRAWLER_CLIENT_POOL_SIZE:10}
  connect:
    timeout:
      millis: ${CRAWLER_CONNECT_TIMEOUT_MILLIS:5000}
  health:
    report:
      interval:
        millis: ${CRAWLER_HEALTH_REPORT_INTERVAL_MILLIS:17000}
  restrict:
    to:
      subdomain: ${CRAWLER_RESTRICT_TO_SUBDOMAIN:true}